### ISSUE TITLE
Cursor jump

### ISSUE THREAD

**Issue by irt-msummers** [fmaclen/svelte-currency-input#77] opened 2024-07-22 21:00 UTC
I am having an issue and I can't figure out what is causing the cursor to jump to the end of text input.  If you just try your demo -$42,069.33 and just type in like 1 before the comma -- its ok and then 2 -- the cursor jumps to the end of the input.  I tried looking at the routine where you make the call `inputElement?.setSelectionRange(endCaretPosition, endCaretPosition);` -- I can't figure out what it is.

Thanks,
Mark

**Comment by fmaclen** [comment] 2024-07-24 03:00
Yeah, this is an annoying bug, there's already an issue for it https://github.com/fmaclen/svelte-currency-input/issues/66, but I haven't had time to look into it yet.

**Comment by fmaclen** [comment] 2024-11-01 21:05
Closing because it's a duplicate of #66

**Closed by fmaclen** 2024-11-01 21:05 UTC
