### ISSUE TITLE
inputClasses.formatted string is not applying TailwindCSS properties

### ISSUE THREAD

**Issue by cassianodaniel** [fmaclen/svelte-currency-input#73] opened 2024-02-04 14:36 UTC
## Description

TailwindCSS properties are not being applied at the `formatted` attribute, on the input custom classes prop.

## Version Used

`"@canutin/svelte-currency-input": "^0.11.3"` 

## Expected Behavior

![image](https://github.com/fmaclen/svelte-currency-input/assets/52015731/763e4173-f64f-473f-b0f2-3994069712b5)

## Actual Behavior

![image](https://github.com/fmaclen/svelte-currency-input/assets/52015731/46268a32-66a0-4ef8-8041-83768295ed87)

## Props Used

List down the props you used with the component, for example:

```svelte
<CurrencyInput
	bind:value
	{name}
	{disabled}
	{placeholder}
	isZeroNullish={true}
	isNegativeAllowed={false}
	locale="en-US"
	currency="USD"
	autocomplete="off"
	inputClasses={{
	         // formatted: 'bg-red-500',
		formattedPositive: 'text-gray-900',
		formattedZero: 'text-gray-900',
		formattedNegative: 'text-gray-900'
	}}
/>
```

## Reproduction Steps

1. Render the component above.
2. Uncomment the commentary in (formatted attribute)
3. All the default styles should be unconsidered (as expected), but the style is not being applied.

## Additional Info

- OS & Version: macOS Sonoma 14.3
- Browser & Version: Google Chrome 121.0.6167.139 (arm64)
- TailwindCSS version: ```^3.0.24```
- Any other relevant details or potential solutions: I suggest taking a look at the data structure of the values returned from the case conditions below, from ```CurrencyInput.svelte```

```svelte
class="
        {inputClasses?.formatted ?? DEFAULT_CLASS_FORMATTED}
        {isNegativeAllowed && !isZero && !isNegative
			? inputClasses?.formattedPositive ?? DEFAULT_CLASS_FORMATTED_POSITIVE
			: ''}
        {isZero ? inputClasses?.formattedZero ?? DEFAULT_CLASS_FORMATTED_ZERO : ''}
        {isNegativeAllowed && isNegative
			? inputClasses?.formattedNegative ?? DEFAULT_CLASS_FORMATTED_NEGATIVE
			: ''}
      "
``` 

When I set 

```svelte
class="bg-red-500"
```

It works fine. But, setting `bg-red-500` hard-coded,

```svelte
class="
        {"bg-red-500" ?? DEFAULT_CLASS_FORMATTED} // changed line
        {isNegativeAllowed && !isZero && !isNegative
			? inputClasses?.formattedPositive ?? DEFAULT_CLASS_FORMATTED_POSITIVE
			: ''}
        {isZero ? inputClasses?.formattedZero ?? DEFAULT_CLASS_FORMATTED_ZERO : ''}
        {isNegativeAllowed && isNegative
			? inputClasses?.formattedNegative ?? DEFAULT_CLASS_FORMATTED_NEGATIVE
			: ''}
      "
``` 

does not.

**Comment by fmaclen** [comment] 2024-02-05 15:53
Thanks for reporting it, I'll take a look.

**Comment by fmaclen** [comment] 2024-02-06 22:50
I'm unable to replicate the issue, here's what I tried:

```svelte
<CurrencyInput
	name="won"
	placeholder={1234.56}
	isNegativeAllowed={false}
	locale="ko-KO"
	currency="KRW"
	inputClasses={{
		formatted: 'bg-red-500',
		formattedPositive: 'text-gray-900',
		formattedZero: 'text-gray-900',
		formattedNegative: 'text-gray-900'
	}}
/>
```

And this is what it looks like:

![image](https://github.com/fmaclen/svelte-currency-input/assets/1434675/86f42bfe-545a-4e70-90cc-f8c04136b466) ![image](https://github.com/fmaclen/svelte-currency-input/assets/1434675/d46f5a86-f509-4351-b3dd-0b8f1a189f16)

Is it possible that `bg-red-500` is being applied correctly but the styles are being overwritten by something else in your project?

If not, could you provide a repository that reproduces this error?

**Comment by fmaclen** [comment] 2024-02-15 03:41
> I can't provide you the code of the project that I am working on based on security policies

That's okay, I don't need to see your entire private repo.

If you can, create a brand new SvelteKit project in a new public repo that includes the minimum amount of dependencies/code that reproduce the issue so I can take a look at it.

**Comment by fmaclen** [comment] 2024-03-18 18:36
Closing due to lack of repro.

**Closed by fmaclen** 2024-03-18 18:36 UTC
Labels: triage
